image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - deploy

variables:
  NAME: gitlab-search
  DOMAIN: groupe-sterne.com
  DATACENTER: ALISE
  HOSTS_CONFIG: STERNE

include: 
  - project: 'Infra/deploiement/hosts'
    ref: main
    file: '${HOSTS_CONFIG}/.hosts-staging.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        ENVIRONMENT: staging
        NAME: st-gitlab-search

build:
  stage: build
  environment: $ENVIRONMENT
  tags:
    - shared-runner
  script:
    - npm install
    - cat "${ENV_VARS}" > .env
    - npm run build
    - mv web.config ./build
    - mv ./build ./publish
  artifacts:
    paths:
      - publish

deploy:
  stage: deploy
  variables:
    ARTIFACT_NAME: build
    PARENT_JOB: build
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
      include:
      - project: infra/deploiement/winrm-iis
        ref: main
        file: ".gitlab-ci.yml"
  when: manual
  allow_failure: false
