image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - deploy

variables:
  DOMAIN: groupe-sterne.com
  HOSTS_CONFIG: STERNE
  ENVIRONMENT: staging
  NAME: st-gitlab-search
  HOSTS: srvstfrtgs1.groupesterne.com

build:
  stage: build
  environment: $ENVIRONMENT
  tags:
    - shared-runner
  script:
    - npm install
    - cat "${ENV_VARS}" > .env
    - npm run build
    - mv web.config ./build
    - mv ./build ./publish
  artifacts:
    paths:
      - publish

deploy:
  stage: deploy
  variables:
    ARTIFACT_NAME: build
    PARENT_JOB: build
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
      include:
      - project: infra/deploiement/winrm-iis
        ref: main
        file: ".gitlab-ci.yml"
  when: on_success
  allow_failure: false
